### ISSUE TITLE
Allow display of passworded servers

### ISSUE THREAD

**Issue by GuntherDP** [reesvarney/acc-server-browser-web#27]
Please consider adding displaying passworded servers. Would also already be helpful if those only display in filtered results (e.g. when filtering on a certain name). Thanks!

**Comment by reesvarney** [comment]
This is something I've looked into a few times before but unfortunately as far as I know its not possible with the method I am using. Basically, right now it replays a websocket request that is generated by the game itself but I haven't been able to understand or modify what data is included in that request as it seems to be encrypted.

As passworded servers are only returned when you include a search term, there is no way to get them with the rest of the servers so to do this it would require manually searching in game and then copying the data for that request. Whilst theoretically this could be made to work with a few specific pre-saved search terms, this would slow down the data fetching process and I think it would be better to consistently have no passworded servers rather than only providing a small subset of them.

I'll come back to this if I ever find a better method or figure out how to construct the requests myself

**Comment by GuntherDP** [comment]
Hi Rees,

Appreciate your feedback. I wasn't aware there was that much additional
complexity involved.  Keep up the good work though!

Cheers,
Gunther
