### ISSUE TITLE
504 Gateway Timeout on /getServers.js

### ISSUE THREAD

**Issue by adamnwerbik** [reesvarney/acc-server-browser-web#29]
No results, page keeps spinning on 'Getting kunos servers'.

I'm getting the same error when cloned using my AUTHKEY and QUERY STRING, possible Kunos changed something on their end?

I don't think it's got anything to do with the nordscheife release as I'm not even able to get any response either.

**Comment by reesvarney** [comment]
Thanks for the report, this has happened fairly commonly in the past whenever the game was updated and was fixed by just getting a new set of auth/ query strings so it might be that, but I will be investigating it as a part of adding GT2/ Nurb24 compatibility.

**Comment by reesvarney** [comment]
Fixed in latest commit and now working at https://acc-server-browser.vercel.app/ .

Clone the latest version and update your query/ auth strings, the format of the query string is slightly different but it should just be one of the websocket messages after the auth message is sent. 

I'll keep the issue open for now so feel free to reply if you are still unable to get it to work locally.

**Comment by adamnwerbik** [comment]
Works for me locally. Thanks for the quick fix.
